/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExpenseHistoryImport } from './routes/expense-history'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AddExpenseImport } from './routes/add-expense'
import { Route as IndexImport } from './routes/index'
import { Route as ExpenseExpenseIdImport } from './routes/expense.$expenseId'

// Create/Update Routes

const ExpenseHistoryRoute = ExpenseHistoryImport.update({
  path: '/expense-history',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AddExpenseRoute = AddExpenseImport.update({
  path: '/add-expense',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExpenseExpenseIdRoute = ExpenseExpenseIdImport.update({
  path: '/expense/$expenseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-expense': {
      id: '/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AddExpenseImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/expense-history': {
      id: '/expense-history'
      path: '/expense-history'
      fullPath: '/expense-history'
      preLoaderRoute: typeof ExpenseHistoryImport
      parentRoute: typeof rootRoute
    }
    '/expense/$expenseId': {
      id: '/expense/$expenseId'
      path: '/expense/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof ExpenseExpenseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AddExpenseRoute,
  DashboardRoute,
  ExpenseHistoryRoute,
  ExpenseExpenseIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-expense",
        "/dashboard",
        "/expense-history",
        "/expense/$expenseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-expense": {
      "filePath": "add-expense.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/expense-history": {
      "filePath": "expense-history.tsx"
    },
    "/expense/$expenseId": {
      "filePath": "expense.$expenseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
